server:
  port: 8084

spring:
#  datasource:
    #MySQL配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.77.220:3306/jiangfendou-mall-pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.77.220
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: jiangfendou-mall-product
  zipkin:
    base-url: http://124.223.77.220:9411/
    discovery-client-enabled: false
    sender:
      type: web
  # 设置抽样采集率100%，默认0.1，即10%
  sleuth:
    sampler:
      probability: 1
  # 初始化dispatcherServlet，默认-1未开启，0及以上为开启
  mvc:
    servlet:
      load-on-startup: 1
  # 解决springboot2.6因为循环引用导致的启动错误
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # cache
  cache:
    type: redis
    # cache-names: qq
    redis:
      # 毫秒
      time-to-live: 3600000
      # key的前缀，如果没有指定前缀 就默认使用缓存名字作为前缀
      # key-prefix: CACHE_
      # use-key-prefix: true
      # 是否缓存空值，防止缓存穿透
      cache-null-values: true
  # 关闭thymeleaf的缓存
  thymeleaf:
    cache: false
  # redis
  redis:
    host: 124.223.77.220
    port: 6379
    password: 123456
  session:
    store-type: redis
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*/xml
#  #主键自增
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.jiangfendou.mall: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'

#配置线程池
jiangfendou:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#-------------------------seata相关配置-------------------------------------------------------------
seata:
  application-id: ${spring.application.name}
  enabled: true
  tx-service-group: my_test_tx_group #此处的配置来源于上述步骤中config.txt中的service.vgroupMapping.my_test_tx_group=default
  registry:
    type: nacos
    nacos:
      server-addr: 124.223.77.220:8848 #nacos的连接地址
      namespace: 2b0b4c20-5368-478b-b7dc-5eb34fb4300f #在nacos中创建的seata命名空间ID
      group: SEATA_GROUP #seata配置的分组名称
      cluster: default
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 124.223.77.220:8848 #nacos的连接地址
      namespace: 2b0b4c20-5368-478b-b7dc-5eb34fb4300f #在nacos中创建的seata命名空间ID
      group: SEATA_GROUP #seata配置的分组名称
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      my_test_tx_group: default #此处的配置来源于上述步骤中config.txt中的service.vgroupMapping.my_test_tx_group=default
      #注意：此处的my_test_tx_group需要和上面seata.tx-service-group以及config.txt中的配置对应

# 开启sentinel对feign的熔断机制
feign:
  sentinel:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug