server:
  port: 8084

spring:
#  datasource:
#    #MySQL配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.77.220:3306/jiangfendou-mall-pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.77.220
  application:
    name: jiangfendou-mall-product
  # 初始化dispatcherServlet，默认-1未开启，0及以上为开启
  mvc:
    servlet:
      load-on-startup: 1
  # 解决springboot2.6因为循环引用导致的启动错误
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # cache
  cache:
    type: redis
    # cache-names: qq
    redis:
      # 毫秒
      time-to-live: 3600000
      # key的前缀，如果没有指定前缀 就默认使用缓存名字作为前缀
      # key-prefix: CACHE_
      # use-key-prefix: true
      # 是否缓存空值，防止缓存穿透
      cache-null-values: true
  # 关闭thymeleaf的缓存
  thymeleaf:
    cache: false
  # redis
  redis:
    host: 124.223.77.220
    port: 6379
    password: 123456
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*/xml
#  #主键自增
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.jiangfendou.mall: debug

#配置线程池
jiangfendou:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

