server:
  port: 8086
spring:
#  datasource:
#    # MySQL配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.77.220:3306/jiangfendou-mall-sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.77.220
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: product_route
          uri: lb://jiangfendou-mall-product
          # 前端项目，/api
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_part_route
          uri: lb://jiangfendou-mall-third-part
          # 前端项目，/api
          predicates:
            - Path=/api/thirdpart/**
          filters:
            - RewritePath=/api/thirdpart/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://jiangfendou-mall-admin
          # 前端项目，/api
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
  application:
    name: jiangfendou-mall-gateway
  # 初始化dispatcherServlet，默认-1未开启，0及以上为开启
  mvc:
    servlet:
      load-on-startup: 1
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*/xml
#  # 主键自增
#  global-config:
#    db-config:
#      id-type: auto
#
#coupon:
#  user:
#    name: jiangfendou
#
#
