server:
  port: 8088

spring:
#  datasource:
#    #MySQL配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.77.220:3306/jiangfendou-mall-pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.77.220
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  application:
    name: jiangfendou-mall-search
  zipkin:
    base-url: http://124.223.77.220:9411/
    discovery-client-enabled: false
    sender:
      type: web
  # 设置抽样采集率100%，默认0.1，即10%
  sleuth:
    sampler:
      probability: 1
  # 初始化dispatcherServlet，默认-1未开启，0及以上为开启
  mvc:
    servlet:
      load-on-startup: 1
  # 解决springboot2.6因为循环引用导致的启动错误
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  # 关闭thymeleaf的缓存
  thymeleaf:
    cache: false
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*/xml
#  #主键自增
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.jiangfendou.mall: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 开启sentinel对feign的熔断机制
feign:
  sentinel:
    enabled: true
