server:
  port: 8087

spring:
#  datasource:
#    #MySQL配置
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://124.223.77.220:3306/jiangfendou-mall-pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: password
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 124.223.77.220
#    alicloud:
#      access-key: LTAI5tCovGXpzjnG7FtSefLc
#      secret-key: snjiQ2oBDGMvlGKzm9nPZ6zV4rvRqH
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#        bucket: jiangfendou
  application:
    name: jiangfendou-mall-third-part
  # 初始化dispatcherServlet，默认-1未开启，0及以上为开启
  mvc:
    servlet:
      load-on-startup: 1
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*/xml
#  #主键自增
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.jiangfendou.mall: debug


